# Generated by Django 3.2.4 on 2021-07-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodDelivery', '0002_auto_20210701_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='orders',
            field=models.ManyToManyField(related_name='food_items', through='foodDelivery.OrderFoodItem', to='foodDelivery.Order'),
        ),
    ]
