# Generated by Django 3.2.4 on 2021-07-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210708_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
